#!/bin/zsh

SEED=(
	/usr/lib/*.dylib
	/etc/*.conf
	/etc/*rc
	/usr/lib/*.dylib
)

FAILURE=()
MINE=(
	"~/Projects/ft_ssl/ft_ssl md5"
	#"~/Projects/ft_ssl/ft_ssl sha256"
)
EXEC=(
	/sbin/md5
	#"openssl sha -sha256 "
)
k=0

for x in `seq 2`; do
	for i in $SEED; do
		eval ${MINE[$x]} $i > /tmp/a
		eval ${EXEC[$x]} $i > /tmp/b

		DIFF=$(diff /tmp/a /tmp/b)
		if [ "$DIFF" != "" ]
		then
			FAILURE+=($i)
		else
			echo "[$k] Test for $i done."
		fi
		k=$((k + 1));
	done
done

echo ""
for x in $FAILURE; do
	echo "Failed test for: $x";
done

t=$((k - ${#FAILURE[@]}));
echo "\nPassed $t/$k tests."
